# PVC for persisting backed up data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: $BACKUP_SIZE
---
# Asbackup job definition 
apiVersion: batch/v1
kind: Job
metadata:
  name: aerospike-backup
spec:
  backoffLimit: 3
  template:
    metadata:
      name: aerospike-backup
    spec:
      containers:
      - command:
        - '/bin/sh'
        - '-c'
        - "asbackup -h $AEROSPIKE_SERVICE_NAME -n $AEROSPIKE_NAMESPACE -s $AEROSPIKE_SET -d /data/"
        image: aerospike/aerospike-tools:latest
        imagePullPolicy: Always
        name: asbackup
        volumeMounts:
        - mountPath: /data
          name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: backup-claim
      restartPolicy: "OnFailure"

