apiVersion: batch/v1
kind: Job
metadata:
  name: aerospike-restore
spec:
  template:
    metadata:
      name: aerospike-restore
    spec:
      containers:
      - command:
        - '/bin/sh'
        - '-c'
        - "asrestore -h $AEROSPIKE_SERVICE_NAME -n $AEROSPIKE_NAMESPACE -s $AEROSPIKE_SET -d /data/"
        image: aerospike/aerospike-tools:latest
        imagePullPolicy: Always
        name: asrestore
        volumeMounts:
        - mountPath: /data
          name: data-volume
      restartPolicy: Never
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: backup-claim
