properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  REPORTING_SECRET:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  IMAGE_AEROSPIKE:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_INIT:
    type: string
    default: $REGISTRY/init:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_UBBAGENT:
    type: string
    default: $REGISTRY/ubbagent:$TAG
    x-google-marketplace:
      type: IMAGE
  AEROSPIKE_NODES:
    title: Server Nodes
    description: The size of your Aerospike Cluster
    type: integer
    default: 3
    minimum: 1
  AEROSPIKE_NAMESPACE:
    title: Aerospike Namespace
    description: The name of your Namespace within Aerospike
    type: string
    default: test
    maxLength: 31
  AEROSPIKE_REPL:
    title: Aerospike Replication Factor
    description: The number of copies of each record that reside in the cluster
    type: integer
    default: 2
    minimum: 1
  AEROSPIKE_MEM:
    title: Aerospike Memory/Persistence Size
    description: The size of your namespace's memory in GB, as well as its persisted storage
    type: integer
    default: 1
    minimum: 1
  AEROSPIKE_TTL:
    title: Aerospike Default TTL
    description: The default TTL of your records in seconds. The default (0) means to never expire.
    type: integer
    default: 0
    minimum: 0 
# Currently unused, will be same as AEROSPIKE_MEM
#  AEROSPIKE_STORAGE:
#    title: Aerospike Storage Size
#    description: The size of your namespace's persisted storage in GB
#    type: integer
#    default: 100
#    minimum: 10
  AEROSPIKE_PERSIST:
    title: Persist Aerospike
    description: Persist your namespace's data to persistent volume claims
    type: boolean
    default: true
required:
-   APP_INSTANCE_NAME
-   NAMESPACE
-   IMAGE_AEROSPIKE
-   IMAGE_UBBAGENT
-   IMAGE_INIT
-   REPORTING_SECRET
-   AEROSPIKE_PERSIST
